In [1]:
import numpy as np

In [2]:
arr= np.array([1,2,3,4,5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arb=np.array([0,1,2,3,4,5,6,7,9,10])

print(arb[1:5])

[1 2 3 4]


In [5]:
print(arr.dtype)

int64


In [11]:
d=np.array([1,2,3,4,5,6,7,8,9,10,11,12],)

print(d.shape)

(12,)


In [12]:
e=d.reshape(4,3)

print(e)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
clear_output




NameError: name 'clear_output' is not defined

In [14]:
for x in d:

    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
