In [1]:
import numpy as np

In [2]:
arr= np.array([1,2,3,4,5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
arb=np.array([0,1,2,3,4,5,6,7,9,10])

print(arb[1:5])

[1 2 3 4]


In [4]:
print(arr.dtype)

int64


In [5]:
d=np.array([1,2,3,4,5,6,7,8,9,10,11,12],)

print(d.shape)

(12,)


In [6]:
e=d.reshape(4,3)

print(e)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
